apiVersion: v1
kind: Service
metadata:
  name: flask-ui
spec:
  selector:
    app: flask-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # Or NodePort, or ClusterIP for internal-only
