apiVersion: v1
kind: Service
metadata:
  name: model-server-service
spec:
  selector:
    app: mochi-model-server
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
